<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Modulo 2 | Propuesta Bookdown</title>
  <meta name="description" content="4 Modulo 2 | Propuesta Bookdown" />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Modulo 2 | Propuesta Bookdown" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Modulo 2 | Propuesta Bookdown" />
  
  
  

<meta name="author" content="Jose Luis Arroyave Capera" />


<meta name="date" content="2023-04-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="modulo-1.html"/>
<link rel="next" href="modulo-3.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="propuesta-bookdown.html"><a href="propuesta-bookdown.html"><i class="fa fa-check"></i><b>1</b> Propuesta Bookdown</a></li>
<li class="chapter" data-level="2" data-path="prediccion-del-precio-de-la-maracuya-para-el-valle-del-cauca.html"><a href="prediccion-del-precio-de-la-maracuya-para-el-valle-del-cauca.html"><i class="fa fa-check"></i><b>2</b> Prediccion del precio de la Maracuya para el Valle del Cauca</a>
<ul>
<li class="chapter" data-level="2.1" data-path="prediccion-del-precio-de-la-maracuya-para-el-valle-del-cauca.html"><a href="prediccion-del-precio-de-la-maracuya-para-el-valle-del-cauca.html#motivación"><i class="fa fa-check"></i><b>2.1</b> Motivación</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="modulo-1.html"><a href="modulo-1.html"><i class="fa fa-check"></i><b>3</b> Modulo 1</a>
<ul>
<li class="chapter" data-level="3.1" data-path="modulo-1.html"><a href="modulo-1.html#unidad-1-motivacion"><i class="fa fa-check"></i><b>3.1</b> Unidad 1: Motivacion</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="modulo-1.html"><a href="modulo-1.html#historico-de-precios-del-maracuya"><i class="fa fa-check"></i><b>3.1.1</b> Historico de precios del Maracuya</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="modulo-1.html"><a href="modulo-1.html#unidad-2-estructura-de-los-datos"><i class="fa fa-check"></i><b>3.2</b> Unidad 2: Estructura de los datos</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="modulo-1.html"><a href="modulo-1.html#estructura-de-los-datos-en-series-de-tiempo-precios-valle"><i class="fa fa-check"></i><b>3.2.1</b> Estructura de los datos en series de tiempo (precios Valle)</a></li>
<li class="chapter" data-level="3.2.2" data-path="modulo-1.html"><a href="modulo-1.html#estructura-de-los-datos-en-series-de-tiempo-precios-passion"><i class="fa fa-check"></i><b>3.2.2</b> Estructura de los datos en series de tiempo (precios Passion)</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="modulo-1.html"><a href="modulo-1.html#unidad-3-preprocesamiento-y-visualización"><i class="fa fa-check"></i><b>3.3</b> Unidad 3: Preprocesamiento y Visualización</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="modulo-1.html"><a href="modulo-1.html#preprocesamiento-y-visualización"><i class="fa fa-check"></i><b>3.3.1</b> Preprocesamiento y visualización</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="modulo-2.html"><a href="modulo-2.html"><i class="fa fa-check"></i><b>4</b> Modulo 2</a>
<ul>
<li class="chapter" data-level="4.1" data-path="modulo-2.html"><a href="modulo-2.html#unidad-1-introduccion-a-los-modelos-de-pronostico"><i class="fa fa-check"></i><b>4.1</b> Unidad 1: Introduccion a los modelos de pronostico</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="modulo-2.html"><a href="modulo-2.html#metodologia-holt-winter"><i class="fa fa-check"></i><b>4.1.1</b> <strong>Metodologia Holt-Winter</strong></a></li>
<li class="chapter" data-level="4.1.2" data-path="modulo-2.html"><a href="modulo-2.html#metodoligia-de-suavizamiento-a-la-variable-tiempo"><i class="fa fa-check"></i><b>4.1.2</b> Metodoligia de Suavizamiento a la variable Tiempo</a></li>
<li class="chapter" data-level="4.1.3" data-path="modulo-2.html"><a href="modulo-2.html#conclusiones-de-aplicacion-de-metodos"><i class="fa fa-check"></i><b>4.1.3</b> Conclusiones de Aplicacion de Metodos</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="modulo-2.html"><a href="modulo-2.html#unidad-2-modelos-estacionarios"><i class="fa fa-check"></i><b>4.2</b> Unidad 2: Modelos Estacionarios</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="modulo-2.html"><a href="modulo-2.html#metodología-box-jenkins"><i class="fa fa-check"></i><b>4.2.1</b> <strong>Metodología Box-Jenkins</strong></a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="modulo-2.html"><a href="modulo-2.html#unidad-3-regresión"><i class="fa fa-check"></i><b>4.3</b> Unidad 3: Regresión</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="modulo-2.html"><a href="modulo-2.html#modelo-propeth"><i class="fa fa-check"></i><b>4.3.1</b> Modelo Propeth</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="modulo-3.html"><a href="modulo-3.html"><i class="fa fa-check"></i><b>5</b> Modulo 3</a>
<ul>
<li class="chapter" data-level="5.1" data-path="modulo-3.html"><a href="modulo-3.html#unidad-1-redes-neuronales-recurrentes"><i class="fa fa-check"></i><b>5.1</b> Unidad 1: Redes Neuronales Recurrentes</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="modulo-3.html"><a href="modulo-3.html#rn-elman"><i class="fa fa-check"></i><b>5.1.1</b> RN Elman</a></li>
<li class="chapter" data-level="5.1.2" data-path="modulo-3.html"><a href="modulo-3.html#rn-jordan"><i class="fa fa-check"></i><b>5.1.2</b> RN Jordan</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Propuesta Bookdown</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modulo-2" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Modulo 2<a href="modulo-2.html#modulo-2" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="sourceCode" id="cb35"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb35-1"><a href="modulo-2.html#cb35-1" aria-hidden="true" tabindex="-1"></a>data.head()</span></code></pre></div>
<pre><code>## fecha
## 2021-01-31    2241.458333
## 2021-02-28    2223.291667
## 2021-03-31    2914.633333
## 2021-04-30    3267.208333
## 2021-05-31    2885.111111
## Freq: M, dtype: float64</code></pre>
<div id="unidad-1-introduccion-a-los-modelos-de-pronostico" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Unidad 1: Introduccion a los modelos de pronostico<a href="modulo-2.html#unidad-1-introduccion-a-los-modelos-de-pronostico" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="metodologia-holt-winter" class="section level3 hasAnchor" number="4.1.1">
<h3><span class="header-section-number">4.1.1</span> <strong>Metodologia Holt-Winter</strong><a href="modulo-2.html#metodologia-holt-winter" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb37"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb37-1"><a href="modulo-2.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb37-2"><a href="modulo-2.html#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb37-3"><a href="modulo-2.html#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="modulo-2.html#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear una figura y un eje</span></span>
<span id="cb37-5"><a href="modulo-2.html#cb37-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb37-6"><a href="modulo-2.html#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="modulo-2.html#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener los valores de fecha y datos</span></span>
<span id="cb37-8"><a href="modulo-2.html#cb37-8" aria-hidden="true" tabindex="-1"></a>fecha <span class="op">=</span> data.index</span>
<span id="cb37-9"><a href="modulo-2.html#cb37-9" aria-hidden="true" tabindex="-1"></a>valor <span class="op">=</span> data.values</span>
<span id="cb37-10"><a href="modulo-2.html#cb37-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-11"><a href="modulo-2.html#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar los puntos de datos</span></span>
<span id="cb37-12"><a href="modulo-2.html#cb37-12" aria-hidden="true" tabindex="-1"></a>ax.plot(fecha, valor, <span class="st">&#39;o&#39;</span>, label<span class="op">=</span><span class="st">&#39;Datos&#39;</span>)</span>
<span id="cb37-13"><a href="modulo-2.html#cb37-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-14"><a href="modulo-2.html#cb37-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar una línea de regresión</span></span>
<span id="cb37-15"><a href="modulo-2.html#cb37-15" aria-hidden="true" tabindex="-1"></a>coef <span class="op">=</span> np.polyfit(<span class="bu">range</span>(<span class="bu">len</span>(fecha)), valor, deg<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb37-16"><a href="modulo-2.html#cb37-16" aria-hidden="true" tabindex="-1"></a>linea_regresion <span class="op">=</span> np.poly1d(coef)</span>
<span id="cb37-17"><a href="modulo-2.html#cb37-17" aria-hidden="true" tabindex="-1"></a>ax.plot(fecha, linea_regresion(<span class="bu">range</span>(<span class="bu">len</span>(fecha))), label<span class="op">=</span><span class="st">&#39;Línea de regresión&#39;</span>)</span>
<span id="cb37-18"><a href="modulo-2.html#cb37-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-19"><a href="modulo-2.html#cb37-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Configurar título y etiquetas de los ejes</span></span>
<span id="cb37-20"><a href="modulo-2.html#cb37-20" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(title<span class="op">=</span><span class="st">&#39;Gráfico de dispersión con línea de regresión&#39;</span>, xlabel<span class="op">=</span><span class="st">&#39;Fecha&#39;</span>, ylabel<span class="op">=</span><span class="st">&#39;Valor&#39;</span>)</span>
<span id="cb37-21"><a href="modulo-2.html#cb37-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-22"><a href="modulo-2.html#cb37-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Rotar las etiquetas del eje x para una mejor visualización</span></span>
<span id="cb37-23"><a href="modulo-2.html#cb37-23" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb37-24"><a href="modulo-2.html#cb37-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-25"><a href="modulo-2.html#cb37-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar la leyenda</span></span></code></pre></div>
<pre><code>## (array([18628., 18718., 18809., 18901., 18993., 19083., 19174., 19266.,
##        19358., 19448., 19539.]), [Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;)])</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb39-1"><a href="modulo-2.html#cb39-1" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb39-2"><a href="modulo-2.html#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="modulo-2.html#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el gráfico</span></span>
<span id="cb39-4"><a href="modulo-2.html#cb39-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="Propuesta-Bookdown_files/figure-html/unnamed-chunk-15-17.png" width="768" /></p>
<p>Ajustamos una ercta de regresion, observando la tendencia creciente de los datos en donde vemos como el precio aumenta a medida que pasa el tiempo.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb40-1"><a href="modulo-2.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb40-2"><a href="modulo-2.html#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb40-3"><a href="modulo-2.html#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb40-4"><a href="modulo-2.html#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="modulo-2.html#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un nuevo DataFrame con la fecha y los datos</span></span>
<span id="cb40-6"><a href="modulo-2.html#cb40-6" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame({<span class="st">&#39;fecha&#39;</span>: data.index, <span class="st">&#39;valor&#39;</span>: data.values})</span>
<span id="cb40-7"><a href="modulo-2.html#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="modulo-2.html#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir la columna de fecha al formato adecuado</span></span>
<span id="cb40-9"><a href="modulo-2.html#cb40-9" aria-hidden="true" tabindex="-1"></a>df[<span class="st">&#39;fecha&#39;</span>] <span class="op">=</span> pd.to_datetime(df[<span class="st">&#39;fecha&#39;</span>])</span>
<span id="cb40-10"><a href="modulo-2.html#cb40-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-11"><a href="modulo-2.html#cb40-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Extraer el mes de cada fecha</span></span>
<span id="cb40-12"><a href="modulo-2.html#cb40-12" aria-hidden="true" tabindex="-1"></a>df[<span class="st">&#39;Month&#39;</span>] <span class="op">=</span> df[<span class="st">&#39;fecha&#39;</span>].dt.month</span>
<span id="cb40-13"><a href="modulo-2.html#cb40-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-14"><a href="modulo-2.html#cb40-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular la desviación del ciclo</span></span>
<span id="cb40-15"><a href="modulo-2.html#cb40-15" aria-hidden="true" tabindex="-1"></a>df[<span class="st">&#39;Desviación del ciclo&#39;</span>] <span class="op">=</span> df[<span class="st">&#39;valor&#39;</span>] <span class="op">-</span> df[<span class="st">&#39;valor&#39;</span>].mean()</span>
<span id="cb40-16"><a href="modulo-2.html#cb40-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-17"><a href="modulo-2.html#cb40-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Trazar el boxplot</span></span>
<span id="cb40-18"><a href="modulo-2.html#cb40-18" aria-hidden="true" tabindex="-1"></a>sns.boxplot(data<span class="op">=</span>df, x<span class="op">=</span><span class="st">&#39;Month&#39;</span>, y<span class="op">=</span><span class="st">&#39;Desviación del ciclo&#39;</span>)</span>
<span id="cb40-19"><a href="modulo-2.html#cb40-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-20"><a href="modulo-2.html#cb40-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Configurar título y etiquetas de los ejes</span></span>
<span id="cb40-21"><a href="modulo-2.html#cb40-21" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">&#39;Boxplot de los datos en función del mes&#39;</span>)</span>
<span id="cb40-22"><a href="modulo-2.html#cb40-22" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">&#39;Mes&#39;</span>)</span>
<span id="cb40-23"><a href="modulo-2.html#cb40-23" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">&#39;Desviación del ciclo&#39;</span>)</span>
<span id="cb40-24"><a href="modulo-2.html#cb40-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-25"><a href="modulo-2.html#cb40-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el gráfico</span></span>
<span id="cb40-26"><a href="modulo-2.html#cb40-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="Propuesta-Bookdown_files/figure-html/unnamed-chunk-16-19.png" width="768" /></p>
<p>Calculamos el ciclo y a traves de la funcion media agregamos nuestro conjunto de datos haciendo una transformacion basica, y ahora a traves de un boxplot tratamos de detectar en cada uno de esos meses la regularidad en lo largo del tiempo, se observa que dentro de los meses de febrero, marzo y abril son bastantes distintos comparado con los meses de fin de año.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb41-1"><a href="modulo-2.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb41-2"><a href="modulo-2.html#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb41-3"><a href="modulo-2.html#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="modulo-2.html#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear una nueva figura y un nuevo eje para el gráfico del logaritmo</span></span>
<span id="cb41-5"><a href="modulo-2.html#cb41-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb41-6"><a href="modulo-2.html#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="modulo-2.html#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicar la transformación logarítmica a los datos</span></span>
<span id="cb41-8"><a href="modulo-2.html#cb41-8" aria-hidden="true" tabindex="-1"></a>log_data <span class="op">=</span> np.log(data)</span>
<span id="cb41-9"><a href="modulo-2.html#cb41-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-10"><a href="modulo-2.html#cb41-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar los datos transformados</span></span>
<span id="cb41-11"><a href="modulo-2.html#cb41-11" aria-hidden="true" tabindex="-1"></a>ax.plot(fecha, log_data)</span>
<span id="cb41-12"><a href="modulo-2.html#cb41-12" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(title<span class="op">=</span><span class="st">&#39;Logaritmo de Precio de Maracuyá&#39;</span>, xlabel<span class="op">=</span><span class="st">&#39;Fecha&#39;</span>, ylabel<span class="op">=</span><span class="st">&#39;log(data)&#39;</span>)</span>
<span id="cb41-13"><a href="modulo-2.html#cb41-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-14"><a href="modulo-2.html#cb41-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Rotar las etiquetas del eje x para una mejor visualización</span></span>
<span id="cb41-15"><a href="modulo-2.html#cb41-15" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb41-16"><a href="modulo-2.html#cb41-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-17"><a href="modulo-2.html#cb41-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el segundo gráfico</span></span></code></pre></div>
<pre><code>## (array([18628., 18718., 18809., 18901., 18993., 19083., 19174., 19266.,
##        19358., 19448., 19539.]), [Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;)])</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb43-1"><a href="modulo-2.html#cb43-1" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="Propuesta-Bookdown_files/figure-html/unnamed-chunk-17-21.png" width="768" /></p>
<p>Utilizamos la funcion logaritmica que nos muestra facilmente los minimos y los maximos de nuestro conjunto de datos, ahora observamos a otra escala la tendencia y estacionalidad ya identificada.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb44-1"><a href="modulo-2.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb44-2"><a href="modulo-2.html#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb44-3"><a href="modulo-2.html#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.holtwinters <span class="im">import</span> ExponentialSmoothing</span>
<span id="cb44-4"><a href="modulo-2.html#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="modulo-2.html#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicar la transformación logarítmica a los datos</span></span>
<span id="cb44-6"><a href="modulo-2.html#cb44-6" aria-hidden="true" tabindex="-1"></a>log_data <span class="op">=</span> np.log(data)</span>
<span id="cb44-7"><a href="modulo-2.html#cb44-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-8"><a href="modulo-2.html#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el modelo Holt-Winters</span></span>
<span id="cb44-9"><a href="modulo-2.html#cb44-9" aria-hidden="true" tabindex="-1"></a>modelo_HW <span class="op">=</span> ExponentialSmoothing(log_data, seasonal<span class="op">=</span><span class="st">&#39;additive&#39;</span>)</span>
<span id="cb44-10"><a href="modulo-2.html#cb44-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-11"><a href="modulo-2.html#cb44-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar el modelo a los datos</span></span>
<span id="cb44-12"><a href="modulo-2.html#cb44-12" aria-hidden="true" tabindex="-1"></a>ajuste_HW <span class="op">=</span> modelo_HW.fit()</span>
<span id="cb44-13"><a href="modulo-2.html#cb44-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-14"><a href="modulo-2.html#cb44-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener las predicciones ajustadas</span></span>
<span id="cb44-15"><a href="modulo-2.html#cb44-15" aria-hidden="true" tabindex="-1"></a>predicciones <span class="op">=</span> ajuste_HW.fittedvalues</span>
<span id="cb44-16"><a href="modulo-2.html#cb44-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-17"><a href="modulo-2.html#cb44-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear una nueva figura y un nuevo eje</span></span>
<span id="cb44-18"><a href="modulo-2.html#cb44-18" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb44-19"><a href="modulo-2.html#cb44-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-20"><a href="modulo-2.html#cb44-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar los datos transformados y las predicciones</span></span>
<span id="cb44-21"><a href="modulo-2.html#cb44-21" aria-hidden="true" tabindex="-1"></a>ax.plot(fecha, log_data, label<span class="op">=</span><span class="st">&#39;Datos&#39;</span>)</span>
<span id="cb44-22"><a href="modulo-2.html#cb44-22" aria-hidden="true" tabindex="-1"></a>ax.plot(fecha, predicciones, label<span class="op">=</span><span class="st">&#39;Predicciones&#39;</span>)</span>
<span id="cb44-23"><a href="modulo-2.html#cb44-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-24"><a href="modulo-2.html#cb44-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Configurar título y etiquetas de los ejes</span></span>
<span id="cb44-25"><a href="modulo-2.html#cb44-25" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(title<span class="op">=</span><span class="st">&#39;Ajuste con Holt-Winters&#39;</span>, xlabel<span class="op">=</span><span class="st">&#39;Fecha&#39;</span>, ylabel<span class="op">=</span><span class="st">&#39;log(data)&#39;</span>)</span>
<span id="cb44-26"><a href="modulo-2.html#cb44-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-27"><a href="modulo-2.html#cb44-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Rotar las etiquetas del eje x para una mejor visualización</span></span>
<span id="cb44-28"><a href="modulo-2.html#cb44-28" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb44-29"><a href="modulo-2.html#cb44-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-30"><a href="modulo-2.html#cb44-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar la leyenda</span></span></code></pre></div>
<pre><code>## (array([18628., 18718., 18809., 18901., 18993., 19083., 19174., 19266.,
##        19358., 19448., 19539.]), [Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;)])</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb46-1"><a href="modulo-2.html#cb46-1" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb46-2"><a href="modulo-2.html#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="modulo-2.html#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el gráfico</span></span>
<span id="cb46-4"><a href="modulo-2.html#cb46-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="Propuesta-Bookdown_files/figure-html/unnamed-chunk-18-23.png" width="768" /></p>
<p>Los datos obtenidos en naranja estan muy cerca y se puede ver que el ajuste con este metodo es relativamente bueno (aunque existen algunos estacios en que se difiere) se observa una grafica que mas o menos sigue el comportamiento del conjunto de datos.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb47-1"><a href="modulo-2.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb47-2"><a href="modulo-2.html#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb47-3"><a href="modulo-2.html#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.seasonal <span class="im">import</span> seasonal_decompose</span>
<span id="cb47-4"><a href="modulo-2.html#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="modulo-2.html#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar la descomposición de los datos ajustados</span></span>
<span id="cb47-6"><a href="modulo-2.html#cb47-6" aria-hidden="true" tabindex="-1"></a>descomposicion <span class="op">=</span> seasonal_decompose(ajuste_HW.fittedvalues)</span>
<span id="cb47-7"><a href="modulo-2.html#cb47-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-8"><a href="modulo-2.html#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener los componentes de la descomposición</span></span>
<span id="cb47-9"><a href="modulo-2.html#cb47-9" aria-hidden="true" tabindex="-1"></a>tendencia <span class="op">=</span> descomposicion.trend</span>
<span id="cb47-10"><a href="modulo-2.html#cb47-10" aria-hidden="true" tabindex="-1"></a>estacionalidad <span class="op">=</span> descomposicion.seasonal</span>
<span id="cb47-11"><a href="modulo-2.html#cb47-11" aria-hidden="true" tabindex="-1"></a>residuos <span class="op">=</span> descomposicion.resid</span>
<span id="cb47-12"><a href="modulo-2.html#cb47-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-13"><a href="modulo-2.html#cb47-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear una nueva figura y subfiguras para cada componente</span></span>
<span id="cb47-14"><a href="modulo-2.html#cb47-14" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">4</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">12</span>))</span>
<span id="cb47-15"><a href="modulo-2.html#cb47-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-16"><a href="modulo-2.html#cb47-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar la tendencia</span></span>
<span id="cb47-17"><a href="modulo-2.html#cb47-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(fecha, tendencia)</span>
<span id="cb47-18"><a href="modulo-2.html#cb47-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].<span class="bu">set</span>(title<span class="op">=</span><span class="st">&#39;Tendencia&#39;</span>, xlabel<span class="op">=</span><span class="st">&#39;Fecha&#39;</span>, ylabel<span class="op">=</span><span class="st">&#39;log(data)&#39;</span>)</span>
<span id="cb47-19"><a href="modulo-2.html#cb47-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-20"><a href="modulo-2.html#cb47-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar la estacionalidad</span></span>
<span id="cb47-21"><a href="modulo-2.html#cb47-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(fecha, estacionalidad)</span>
<span id="cb47-22"><a href="modulo-2.html#cb47-22" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].<span class="bu">set</span>(title<span class="op">=</span><span class="st">&#39;Estacionalidad&#39;</span>, xlabel<span class="op">=</span><span class="st">&#39;Fecha&#39;</span>, ylabel<span class="op">=</span><span class="st">&#39;log(data)&#39;</span>)</span>
<span id="cb47-23"><a href="modulo-2.html#cb47-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-24"><a href="modulo-2.html#cb47-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar los residuos</span></span>
<span id="cb47-25"><a href="modulo-2.html#cb47-25" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].plot(fecha, residuos)</span>
<span id="cb47-26"><a href="modulo-2.html#cb47-26" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].<span class="bu">set</span>(title<span class="op">=</span><span class="st">&#39;Residuos&#39;</span>, xlabel<span class="op">=</span><span class="st">&#39;Fecha&#39;</span>, ylabel<span class="op">=</span><span class="st">&#39;log(data)&#39;</span>)</span>
<span id="cb47-27"><a href="modulo-2.html#cb47-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-28"><a href="modulo-2.html#cb47-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar los datos originales</span></span>
<span id="cb47-29"><a href="modulo-2.html#cb47-29" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">3</span>].plot(fecha, log_data, label<span class="op">=</span><span class="st">&#39;Datos&#39;</span>)</span>
<span id="cb47-30"><a href="modulo-2.html#cb47-30" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">3</span>].<span class="bu">set</span>(title<span class="op">=</span><span class="st">&#39;Datos Originales&#39;</span>, xlabel<span class="op">=</span><span class="st">&#39;Fecha&#39;</span>, ylabel<span class="op">=</span><span class="st">&#39;log(data)&#39;</span>)</span>
<span id="cb47-31"><a href="modulo-2.html#cb47-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-32"><a href="modulo-2.html#cb47-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar el espaciado entre las subfiguras</span></span>
<span id="cb47-33"><a href="modulo-2.html#cb47-33" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb47-34"><a href="modulo-2.html#cb47-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-35"><a href="modulo-2.html#cb47-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el gráfico</span></span>
<span id="cb47-36"><a href="modulo-2.html#cb47-36" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="Propuesta-Bookdown_files/figure-html/unnamed-chunk-19-25.png" width="768" /></p>
<div class="sourceCode" id="cb48"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb48-1"><a href="modulo-2.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb48-2"><a href="modulo-2.html#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.holtwinters <span class="im">import</span> ExponentialSmoothing</span>
<span id="cb48-3"><a href="modulo-2.html#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="modulo-2.html#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el modelo Holt-Winters</span></span>
<span id="cb48-5"><a href="modulo-2.html#cb48-5" aria-hidden="true" tabindex="-1"></a>modelo_HW <span class="op">=</span> ExponentialSmoothing(log_data, seasonal<span class="op">=</span><span class="st">&#39;additive&#39;</span>)</span>
<span id="cb48-6"><a href="modulo-2.html#cb48-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-7"><a href="modulo-2.html#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar el modelo</span></span>
<span id="cb48-8"><a href="modulo-2.html#cb48-8" aria-hidden="true" tabindex="-1"></a>modelo_ajustado <span class="op">=</span> modelo_HW.fit()</span>
<span id="cb48-9"><a href="modulo-2.html#cb48-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-10"><a href="modulo-2.html#cb48-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar la predicción de 4 periodos hacia adelante</span></span>
<span id="cb48-11"><a href="modulo-2.html#cb48-11" aria-hidden="true" tabindex="-1"></a>prediccion <span class="op">=</span> modelo_ajustado.forecast(steps<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb48-12"><a href="modulo-2.html#cb48-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-13"><a href="modulo-2.html#cb48-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear una nueva figura y un nuevo eje</span></span>
<span id="cb48-14"><a href="modulo-2.html#cb48-14" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb48-15"><a href="modulo-2.html#cb48-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-16"><a href="modulo-2.html#cb48-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar los datos originales</span></span>
<span id="cb48-17"><a href="modulo-2.html#cb48-17" aria-hidden="true" tabindex="-1"></a>ax.plot(fecha, log_data, label<span class="op">=</span><span class="st">&#39;Datos&#39;</span>)</span>
<span id="cb48-18"><a href="modulo-2.html#cb48-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-19"><a href="modulo-2.html#cb48-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener las fechas para los valores predichos</span></span>
<span id="cb48-20"><a href="modulo-2.html#cb48-20" aria-hidden="true" tabindex="-1"></a>fechas_prediccion <span class="op">=</span> pd.date_range(start<span class="op">=</span>fecha[<span class="op">-</span><span class="dv">1</span>], periods<span class="op">=</span><span class="bu">len</span>(prediccion)<span class="op">+</span><span class="dv">1</span>, freq<span class="op">=</span><span class="st">&#39;M&#39;</span>)[<span class="dv">1</span>:]</span>
<span id="cb48-21"><a href="modulo-2.html#cb48-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-22"><a href="modulo-2.html#cb48-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar los valores predichos</span></span>
<span id="cb48-23"><a href="modulo-2.html#cb48-23" aria-hidden="true" tabindex="-1"></a>ax.plot(fechas_prediccion, prediccion, label<span class="op">=</span><span class="st">&#39;Valores Predichos&#39;</span>)</span>
<span id="cb48-24"><a href="modulo-2.html#cb48-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-25"><a href="modulo-2.html#cb48-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Configurar título y etiquetas de los ejes</span></span>
<span id="cb48-26"><a href="modulo-2.html#cb48-26" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(title<span class="op">=</span><span class="st">&#39;Predicción con Holt-Winters&#39;</span>, xlabel<span class="op">=</span><span class="st">&#39;Fecha&#39;</span>, ylabel<span class="op">=</span><span class="st">&#39;log(data)&#39;</span>)</span>
<span id="cb48-27"><a href="modulo-2.html#cb48-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-28"><a href="modulo-2.html#cb48-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Rotar las etiquetas del eje x para una mejor visualización</span></span>
<span id="cb48-29"><a href="modulo-2.html#cb48-29" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb48-30"><a href="modulo-2.html#cb48-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-31"><a href="modulo-2.html#cb48-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar la leyenda</span></span></code></pre></div>
<pre><code>## (array([18628., 18748., 18871., 18993., 19113., 19236., 19358., 19478.,
##        19601.]), [Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;)])</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb50-1"><a href="modulo-2.html#cb50-1" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb50-2"><a href="modulo-2.html#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="modulo-2.html#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el gráfico</span></span>
<span id="cb50-4"><a href="modulo-2.html#cb50-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="Propuesta-Bookdown_files/figure-html/unnamed-chunk-20-27.png" width="768" /></p>
<p>Podemos ver una prediccion utilizando el modelo Holt-Winter para los precios de junio, julio, agosto y septiembre del año 2023.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb51-1"><a href="modulo-2.html#cb51-1" aria-hidden="true" tabindex="-1"></a>prediccion.head()</span></code></pre></div>
<pre><code>## 2023-06-30    8.224309
## 2023-07-31    8.355440
## 2023-08-31    8.169870
## 2023-09-30    8.305518
## Freq: M, dtype: float64</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb53-1"><a href="modulo-2.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb53-2"><a href="modulo-2.html#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="modulo-2.html#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir los valores predichos del logaritmo al valor real</span></span>
<span id="cb53-4"><a href="modulo-2.html#cb53-4" aria-hidden="true" tabindex="-1"></a>valores_predichos <span class="op">=</span> np.exp(prediccion)</span>
<span id="cb53-5"><a href="modulo-2.html#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="modulo-2.html#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir los valores predichos en formato fecha y valor</span></span>
<span id="cb53-7"><a href="modulo-2.html#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> fecha_pred, valor_pred <span class="kw">in</span> <span class="bu">zip</span>(fechas_prediccion, valores_predichos):</span>
<span id="cb53-8"><a href="modulo-2.html#cb53-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(fecha_pred.strftime(<span class="st">&#39;%Y-%m-</span><span class="sc">%d</span><span class="st">&#39;</span>), valor_pred)</span></code></pre></div>
<pre><code>## 2023-06-30 3730.543176939008
## 2023-07-31 4253.255902042168
## 2023-08-31 3532.8863697415463
## 2023-09-30 4046.1378831789025</code></pre>
</div>
<div id="metodoligia-de-suavizamiento-a-la-variable-tiempo" class="section level3 hasAnchor" number="4.1.2">
<h3><span class="header-section-number">4.1.2</span> Metodoligia de Suavizamiento a la variable Tiempo<a href="modulo-2.html#metodoligia-de-suavizamiento-a-la-variable-tiempo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb55"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb55-1"><a href="modulo-2.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb55-2"><a href="modulo-2.html#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.api <span class="im">import</span> SimpleExpSmoothing</span>
<span id="cb55-3"><a href="modulo-2.html#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="modulo-2.html#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el modelo de suavizamiento exponencial simple</span></span>
<span id="cb55-5"><a href="modulo-2.html#cb55-5" aria-hidden="true" tabindex="-1"></a>modelo_ses <span class="op">=</span> SimpleExpSmoothing(log_data)</span>
<span id="cb55-6"><a href="modulo-2.html#cb55-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-7"><a href="modulo-2.html#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar el modelo</span></span>
<span id="cb55-8"><a href="modulo-2.html#cb55-8" aria-hidden="true" tabindex="-1"></a>modelo_ajustado <span class="op">=</span> modelo_ses.fit()</span>
<span id="cb55-9"><a href="modulo-2.html#cb55-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-10"><a href="modulo-2.html#cb55-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar la predicción de 4 periodos hacia adelante</span></span>
<span id="cb55-11"><a href="modulo-2.html#cb55-11" aria-hidden="true" tabindex="-1"></a>prediccion <span class="op">=</span> modelo_ajustado.forecast(steps<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb55-12"><a href="modulo-2.html#cb55-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-13"><a href="modulo-2.html#cb55-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear una nueva figura y un nuevo eje</span></span>
<span id="cb55-14"><a href="modulo-2.html#cb55-14" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb55-15"><a href="modulo-2.html#cb55-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-16"><a href="modulo-2.html#cb55-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar los datos originales</span></span>
<span id="cb55-17"><a href="modulo-2.html#cb55-17" aria-hidden="true" tabindex="-1"></a>ax.plot(fecha, log_data, label<span class="op">=</span><span class="st">&#39;Datos&#39;</span>)</span>
<span id="cb55-18"><a href="modulo-2.html#cb55-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-19"><a href="modulo-2.html#cb55-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener las fechas para los valores predichos</span></span>
<span id="cb55-20"><a href="modulo-2.html#cb55-20" aria-hidden="true" tabindex="-1"></a>fechas_prediccion <span class="op">=</span> pd.date_range(start<span class="op">=</span>fecha[<span class="op">-</span><span class="dv">1</span>], periods<span class="op">=</span><span class="bu">len</span>(prediccion)<span class="op">+</span><span class="dv">1</span>, freq<span class="op">=</span><span class="st">&#39;M&#39;</span>)[<span class="dv">1</span>:]</span>
<span id="cb55-21"><a href="modulo-2.html#cb55-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-22"><a href="modulo-2.html#cb55-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar los valores predichos</span></span>
<span id="cb55-23"><a href="modulo-2.html#cb55-23" aria-hidden="true" tabindex="-1"></a>ax.plot(fechas_prediccion, prediccion, label<span class="op">=</span><span class="st">&#39;Valores Predichos&#39;</span>)</span>
<span id="cb55-24"><a href="modulo-2.html#cb55-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-25"><a href="modulo-2.html#cb55-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Configurar título y etiquetas de los ejes</span></span>
<span id="cb55-26"><a href="modulo-2.html#cb55-26" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(title<span class="op">=</span><span class="st">&#39;Predicción con Suavizamiento Exponencial Simple&#39;</span>, xlabel<span class="op">=</span><span class="st">&#39;Fecha&#39;</span>, ylabel<span class="op">=</span><span class="st">&#39;log(data)&#39;</span>)</span>
<span id="cb55-27"><a href="modulo-2.html#cb55-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-28"><a href="modulo-2.html#cb55-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Rotar las etiquetas del eje x para una mejor visualización</span></span>
<span id="cb55-29"><a href="modulo-2.html#cb55-29" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb55-30"><a href="modulo-2.html#cb55-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-31"><a href="modulo-2.html#cb55-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar la leyenda</span></span></code></pre></div>
<pre><code>## (array([18628., 18748., 18871., 18993., 19113., 19236., 19358., 19478.,
##        19601.]), [Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;), Text(0, 0, &#39;&#39;)])</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb57-1"><a href="modulo-2.html#cb57-1" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb57-2"><a href="modulo-2.html#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="modulo-2.html#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el gráfico</span></span>
<span id="cb57-4"><a href="modulo-2.html#cb57-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="Propuesta-Bookdown_files/figure-html/unnamed-chunk-23-29.png" width="768" /></p>
<div class="sourceCode" id="cb58"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb58-1"><a href="modulo-2.html#cb58-1" aria-hidden="true" tabindex="-1"></a>prediccion.head()</span></code></pre></div>
<pre><code>## 2023-06-30    8.409658
## 2023-07-31    8.409658
## 2023-08-31    8.409658
## 2023-09-30    8.409658
## Freq: M, dtype: float64</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb60-1"><a href="modulo-2.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb60-2"><a href="modulo-2.html#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="modulo-2.html#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir los valores predichos del logaritmo al valor real</span></span>
<span id="cb60-4"><a href="modulo-2.html#cb60-4" aria-hidden="true" tabindex="-1"></a>valores_predichos <span class="op">=</span> np.exp(prediccion)</span>
<span id="cb60-5"><a href="modulo-2.html#cb60-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-6"><a href="modulo-2.html#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir los valores predichos en formato fecha y valor</span></span>
<span id="cb60-7"><a href="modulo-2.html#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> fecha_pred, valor_pred <span class="kw">in</span> <span class="bu">zip</span>(fechas_prediccion, valores_predichos):</span>
<span id="cb60-8"><a href="modulo-2.html#cb60-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(fecha_pred.strftime(<span class="st">&#39;%Y-%m-</span><span class="sc">%d</span><span class="st">&#39;</span>), valor_pred)</span></code></pre></div>
<pre><code>## 2023-06-30 4490.222478590083
## 2023-07-31 4490.222478590083
## 2023-08-31 4490.222478590083
## 2023-09-30 4490.222478590083</code></pre>
</div>
<div id="conclusiones-de-aplicacion-de-metodos" class="section level3 hasAnchor" number="4.1.3">
<h3><span class="header-section-number">4.1.3</span> Conclusiones de Aplicacion de Metodos<a href="modulo-2.html#conclusiones-de-aplicacion-de-metodos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Mediante el método Holt-Winters se obtienen predicciones como 3.730 (Junio/23), 4.253 (Julio/23), 3.523 (Agosto/23) y 4.046 (Septiembre/23). Por otro lado, al aplicar el método de suavizamiento a la variable tiempo para los mismos periodos se obtuvo un valor de 4.490. Esta discrepancia puede deberse a varios factores. En primer lugar, el método de suavizamiento de la variable tiempo puede no estar capturando adecuadamente las variaciones en los datos debido a su configuración de parámetros o a la falta de patrones distintivos en la serie temporal. Además, el método de Holt-Winters está diseñado específicamente para abordar problemas de tendencia y estacionalidad, lo que puede hacerlo más adecuado para este tipo de series. Aunque no es la solución definitiva para todos los casos, el método de Holt-Winters proporciona una base sólida para obtener resultados aceptables y permite una interpretación más clara incluso para aquellos que no son expertos técnicos. En última instancia, es importante evaluar y comparar diferentes técnicas de pronóstico para determinar la más adecuada para cada situación específica.</p>
</div>
</div>
<div id="unidad-2-modelos-estacionarios" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Unidad 2: Modelos Estacionarios<a href="modulo-2.html#unidad-2-modelos-estacionarios" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="metodología-box-jenkins" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> <strong>Metodología Box-Jenkins</strong><a href="modulo-2.html#metodología-box-jenkins" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb62"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb62-1"><a href="modulo-2.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb62-2"><a href="modulo-2.html#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.graphics.tsaplots <span class="im">import</span> plot_acf, plot_pacf</span>
<span id="cb62-3"><a href="modulo-2.html#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib</span>
<span id="cb62-4"><a href="modulo-2.html#cb62-4" aria-hidden="true" tabindex="-1"></a>matplotlib.use(<span class="st">&#39;QtAgg&#39;</span>)</span>
<span id="cb62-5"><a href="modulo-2.html#cb62-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-6"><a href="modulo-2.html#cb62-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular la ACF</span></span>
<span id="cb62-7"><a href="modulo-2.html#cb62-7" aria-hidden="true" tabindex="-1"></a>acf <span class="op">=</span> plot_acf(data)</span>
<span id="cb62-8"><a href="modulo-2.html#cb62-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-9"><a href="modulo-2.html#cb62-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular la PACF con 7 retrasos</span></span>
<span id="cb62-10"><a href="modulo-2.html#cb62-10" aria-hidden="true" tabindex="-1"></a>pacf <span class="op">=</span> plot_pacf(data, lags<span class="op">=</span><span class="dv">7</span>, method<span class="op">=</span><span class="st">&#39;ywm&#39;</span>)</span>
<span id="cb62-11"><a href="modulo-2.html#cb62-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-12"><a href="modulo-2.html#cb62-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los gráficos de la ACF y PACF</span></span>
<span id="cb62-13"><a href="modulo-2.html#cb62-13" aria-hidden="true" tabindex="-1"></a>acf.show()</span>
<span id="cb62-14"><a href="modulo-2.html#cb62-14" aria-hidden="true" tabindex="-1"></a>pacf.show()</span></code></pre></div>
<p>Utilizamos un bucle para encontrar la mejor combinacion ARIMA, iterando sobre diferentes combinaciones para luego seleccionar el modelo con el menor valor de la metrica de evaluacion. Cabe mencionar que esto es una implementacion basica y que existen técnicas más avanzadas, como la validación cruzada, para evaluar y seleccionar modelos ARIMA. Sin embargo, este enfoque de búsqueda exhaustiva brinda un punto de partida para explorar diferentes combinaciones de órdenes y encontrar un modelo ARIMA adecuado para los datos.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb63-1"><a href="modulo-2.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> itertools</span>
<span id="cb63-2"><a href="modulo-2.html#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb63-3"><a href="modulo-2.html#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.arima.model <span class="im">import</span> ARIMA</span>
<span id="cb63-4"><a href="modulo-2.html#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="modulo-2.html#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Definir los rangos para los órdenes p, d, q</span></span>
<span id="cb63-6"><a href="modulo-2.html#cb63-6" aria-hidden="true" tabindex="-1"></a>p_range <span class="op">=</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">3</span>)  <span class="co"># Rango para el orden AR(p)</span></span>
<span id="cb63-7"><a href="modulo-2.html#cb63-7" aria-hidden="true" tabindex="-1"></a>d_range <span class="op">=</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">2</span>)  <span class="co"># Rango para el orden de diferenciación d</span></span>
<span id="cb63-8"><a href="modulo-2.html#cb63-8" aria-hidden="true" tabindex="-1"></a>q_range <span class="op">=</span> <span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">3</span>)  <span class="co"># Rango para el orden MA(q)</span></span>
<span id="cb63-9"><a href="modulo-2.html#cb63-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-10"><a href="modulo-2.html#cb63-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Lista para almacenar los resultados de los modelos</span></span>
<span id="cb63-11"><a href="modulo-2.html#cb63-11" aria-hidden="true" tabindex="-1"></a>model_results <span class="op">=</span> []</span>
<span id="cb63-12"><a href="modulo-2.html#cb63-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-13"><a href="modulo-2.html#cb63-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Ignorar los warnings para evitar la impresión repetitiva de los mismos</span></span>
<span id="cb63-14"><a href="modulo-2.html#cb63-14" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">&quot;ignore&quot;</span>)</span>
<span id="cb63-15"><a href="modulo-2.html#cb63-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-16"><a href="modulo-2.html#cb63-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Iterar sobre todas las combinaciones posibles de órdenes</span></span>
<span id="cb63-17"><a href="modulo-2.html#cb63-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p, d, q <span class="kw">in</span> itertools.product(p_range, d_range, q_range):</span>
<span id="cb63-18"><a href="modulo-2.html#cb63-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb63-19"><a href="modulo-2.html#cb63-19" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Ajustar el modelo ARIMA</span></span>
<span id="cb63-20"><a href="modulo-2.html#cb63-20" aria-hidden="true" tabindex="-1"></a>        modelo <span class="op">=</span> ARIMA(data, order<span class="op">=</span>(p, d, q))</span>
<span id="cb63-21"><a href="modulo-2.html#cb63-21" aria-hidden="true" tabindex="-1"></a>        modelo_ajustado <span class="op">=</span> modelo.fit()</span>
<span id="cb63-22"><a href="modulo-2.html#cb63-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-23"><a href="modulo-2.html#cb63-23" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Calcular la métrica de evaluación (por ejemplo, AIC)</span></span>
<span id="cb63-24"><a href="modulo-2.html#cb63-24" aria-hidden="true" tabindex="-1"></a>        aic <span class="op">=</span> modelo_ajustado.aic</span>
<span id="cb63-25"><a href="modulo-2.html#cb63-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-26"><a href="modulo-2.html#cb63-26" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Almacenar los resultados del modelo y su orden correspondiente</span></span>
<span id="cb63-27"><a href="modulo-2.html#cb63-27" aria-hidden="true" tabindex="-1"></a>        model_results.append((p, d, q, aic))</span>
<span id="cb63-28"><a href="modulo-2.html#cb63-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span>:</span>
<span id="cb63-29"><a href="modulo-2.html#cb63-29" aria-hidden="true" tabindex="-1"></a>        <span class="cf">continue</span></span>
<span id="cb63-30"><a href="modulo-2.html#cb63-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-31"><a href="modulo-2.html#cb63-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordenar los resultados por la métrica de evaluación (menor AIC)</span></span>
<span id="cb63-32"><a href="modulo-2.html#cb63-32" aria-hidden="true" tabindex="-1"></a>model_results.sort(key<span class="op">=</span><span class="kw">lambda</span> x: x[<span class="dv">3</span>])</span>
<span id="cb63-33"><a href="modulo-2.html#cb63-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-34"><a href="modulo-2.html#cb63-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener la mejor combinación ARIMA</span></span>
<span id="cb63-35"><a href="modulo-2.html#cb63-35" aria-hidden="true" tabindex="-1"></a>best_order <span class="op">=</span> model_results[<span class="dv">0</span>][:<span class="dv">3</span>]</span>
<span id="cb63-36"><a href="modulo-2.html#cb63-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-37"><a href="modulo-2.html#cb63-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar el modelo final con la mejor combinación de órdenes</span></span>
<span id="cb63-38"><a href="modulo-2.html#cb63-38" aria-hidden="true" tabindex="-1"></a>best_model <span class="op">=</span> ARIMA(data, order<span class="op">=</span>best_order)</span>
<span id="cb63-39"><a href="modulo-2.html#cb63-39" aria-hidden="true" tabindex="-1"></a>best_model_ajustado <span class="op">=</span> best_model.fit()</span>
<span id="cb63-40"><a href="modulo-2.html#cb63-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-41"><a href="modulo-2.html#cb63-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir los resultados del mejor modelo</span></span>
<span id="cb63-42"><a href="modulo-2.html#cb63-42" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(best_model_ajustado.summary())</span></code></pre></div>
<pre><code>##                                SARIMAX Results                                
## ==============================================================================
## Dep. Variable:                      y   No. Observations:                   29
## Model:                 ARIMA(0, 1, 2)   Log Likelihood                -213.261
## Date:              mar., 20 jun. 2023   AIC                            432.523
## Time:                        00:54:35   BIC                            436.519
## Sample:                    01-31-2021   HQIC                           433.745
##                          - 05-31-2023                                         
## Covariance Type:                  opg                                         
## ==============================================================================
##                  coef    std err          z      P&gt;|z|      [0.025      0.975]
## ------------------------------------------------------------------------------
## ma.L1         -0.1058      0.160     -0.662      0.508      -0.419       0.208
## ma.L2         -0.3985      0.200     -1.993      0.046      -0.790      -0.007
## sigma2      2.303e+05   7.82e+04      2.945      0.003     7.7e+04    3.83e+05
## ===================================================================================
## Ljung-Box (L1) (Q):                   0.56   Jarque-Bera (JB):                 0.65
## Prob(Q):                              0.45   Prob(JB):                         0.72
## Heteroskedasticity (H):               0.86   Skew:                            -0.25
## Prob(H) (two-sided):                  0.82   Kurtosis:                         2.44
## ===================================================================================
## 
## Warnings:
## [1] Covariance matrix calculated using the outer product of gradients (complex-step).</code></pre>
<p>Los resultados del modelo ARIMA (0, 1, 2) indican lo siguiente:</p>
<ul>
<li><p>La variable “y” corresponde a la serie de tiempo que estás analizando, con 29 observaciones en total.</p></li>
<li><p>El modelo ajustado tiene un AIC (Criterio de Información de Akaike) de 432.523, lo cual indica que este modelo tiene un buen ajuste a los datos.</p></li>
<li><p>Los coeficientes estimados para los dos términos de media móvil (MA) son -0.1058 y -0.3985. Estos coeficientes representan la influencia de los errores pasados en las predicciones actuales. Los valores cercanos a cero indican que los términos de media móvil no tienen un efecto significativo en el modelo.</p></li>
<li><p>El valor de sigma2 es de 2.303e+05, que representa la varianza estimada del ruido blanco en el modelo.</p></li>
<li><p>El valor p para el estadístico Ljung-Box (L1) es de 0.56, y el valor p para el estadístico de Jarque-Bera (JB) es de 0.65. Estos valores se utilizan para evaluar la autocorrelación y la normalidad de los residuos del modelo. Valores altos de p indican que los residuos no presentan autocorrelación significativa y siguen una distribución normal.</p></li>
</ul>
<div class="sourceCode" id="cb65"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb65-1"><a href="modulo-2.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb65-2"><a href="modulo-2.html#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.tsa.arima.model <span class="im">import</span> ARIMA</span>
<span id="cb65-3"><a href="modulo-2.html#cb65-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-4"><a href="modulo-2.html#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar el modelo ARIMA</span></span>
<span id="cb65-5"><a href="modulo-2.html#cb65-5" aria-hidden="true" tabindex="-1"></a>modelo <span class="op">=</span> ARIMA(data, order<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb65-6"><a href="modulo-2.html#cb65-6" aria-hidden="true" tabindex="-1"></a>modelo_ajustado <span class="op">=</span> modelo.fit()</span>
<span id="cb65-7"><a href="modulo-2.html#cb65-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-8"><a href="modulo-2.html#cb65-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar la predicción para los siguientes 4 meses</span></span>
<span id="cb65-9"><a href="modulo-2.html#cb65-9" aria-hidden="true" tabindex="-1"></a>prediccion <span class="op">=</span> modelo_ajustado.get_forecast(steps<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb65-10"><a href="modulo-2.html#cb65-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-11"><a href="modulo-2.html#cb65-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtener los valores predichos y los intervalos de confianza</span></span>
<span id="cb65-12"><a href="modulo-2.html#cb65-12" aria-hidden="true" tabindex="-1"></a>valores_predichos <span class="op">=</span> prediccion.predicted_mean</span>
<span id="cb65-13"><a href="modulo-2.html#cb65-13" aria-hidden="true" tabindex="-1"></a>intervalos_confianza <span class="op">=</span> prediccion.conf_int()</span>
<span id="cb65-14"><a href="modulo-2.html#cb65-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-15"><a href="modulo-2.html#cb65-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un DataFrame con los resultados</span></span>
<span id="cb65-16"><a href="modulo-2.html#cb65-16" aria-hidden="true" tabindex="-1"></a>prediccion_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb65-17"><a href="modulo-2.html#cb65-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">&#39;Fecha&#39;</span>: valores_predichos.index,</span>
<span id="cb65-18"><a href="modulo-2.html#cb65-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">&#39;Predicción&#39;</span>: valores_predichos.values,</span>
<span id="cb65-19"><a href="modulo-2.html#cb65-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">&#39;Intervalo de Confianza Inferior&#39;</span>: intervalos_confianza.iloc[:, <span class="dv">0</span>].values,</span>
<span id="cb65-20"><a href="modulo-2.html#cb65-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">&#39;Intervalo de Confianza Superior&#39;</span>: intervalos_confianza.iloc[:, <span class="dv">1</span>].values</span>
<span id="cb65-21"><a href="modulo-2.html#cb65-21" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb65-22"><a href="modulo-2.html#cb65-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-23"><a href="modulo-2.html#cb65-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir los resultados</span></span>
<span id="cb65-24"><a href="modulo-2.html#cb65-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(prediccion_df)</span></code></pre></div>
<pre><code>##        Fecha  ...  Intervalo de Confianza Superior
## 0 2023-06-30  ...                      5003.674861
## 1 2023-07-31  ...                      5575.663394
## 2 2023-08-31  ...                      5659.043617
## 3 2023-09-30  ...                      5737.548398
## 
## [4 rows x 4 columns]</code></pre>
</div>
</div>
<div id="unidad-3-regresión" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Unidad 3: Regresión<a href="modulo-2.html#unidad-3-regresión" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="modelo-propeth" class="section level3 hasAnchor" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Modelo Propeth<a href="modulo-2.html#modelo-propeth" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb67"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb67-1"><a href="modulo-2.html#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co">#from fbprophet import Prophet</span></span>
<span id="cb67-2"><a href="modulo-2.html#cb67-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-3"><a href="modulo-2.html#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="co">#data = data.rename(columns={&#39;fecha&#39;: &#39;ds&#39;, &#39;valor&#39;: &#39;y&#39;})</span></span>
<span id="cb67-4"><a href="modulo-2.html#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="co">#modelo = Prophet()</span></span>
<span id="cb67-5"><a href="modulo-2.html#cb67-5" aria-hidden="true" tabindex="-1"></a><span class="co">#modelo.fit(data)</span></span>
<span id="cb67-6"><a href="modulo-2.html#cb67-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-7"><a href="modulo-2.html#cb67-7" aria-hidden="true" tabindex="-1"></a><span class="co">#futuro = modelo.make_future_dataframe(periods=12)  # Predicción de 12 días futuros</span></span>
<span id="cb67-8"><a href="modulo-2.html#cb67-8" aria-hidden="true" tabindex="-1"></a><span class="co">#prediccion = modelo.predict(futuro)</span></span>
<span id="cb67-9"><a href="modulo-2.html#cb67-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-10"><a href="modulo-2.html#cb67-10" aria-hidden="true" tabindex="-1"></a><span class="co">#modelo.plot(prediccion)</span></span></code></pre></div>
<p>Por limitaciones computacionales no ha sido posible la instalacion del paquete Prophet. Se intento instalar pero no se encuentra la liibreria fbprophet para Python. (Solo esta seccion se realizara en R)</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="modulo-2.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar los datos desde un archivo CSV</span></span>
<span id="cb68-2"><a href="modulo-2.html#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code></pre></div>
<pre><code>## Warning: package &#39;readxl&#39; was built under R version 4.2.3</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="modulo-2.html#cb70-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;historico_precios_maracuya.xlsx&quot;</span>, <span class="at">sheet =</span> <span class="st">&quot;Hoja1&quot;</span>)</span>
<span id="cb70-2"><a href="modulo-2.html#cb70-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-3"><a href="modulo-2.html#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar el paquete &quot;lubridate&quot;</span></span>
<span id="cb70-4"><a href="modulo-2.html#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span></code></pre></div>
<pre><code>## Warning: package &#39;lubridate&#39; was built under R version 4.2.3</code></pre>
<pre><code>## 
## Attaching package: &#39;lubridate&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     date, intersect, setdiff, union</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="modulo-2.html#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar el paquete &quot;dplyr&quot;</span></span>
<span id="cb74-2"><a href="modulo-2.html#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="modulo-2.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir las columnas de fecha al formato adecuado</span></span>
<span id="cb78-2"><a href="modulo-2.html#cb78-2" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>fecha <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(data<span class="sc">$</span>fecha)</span>
<span id="cb78-3"><a href="modulo-2.html#cb78-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-4"><a href="modulo-2.html#cb78-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Desagrupar los datos</span></span>
<span id="cb78-5"><a href="modulo-2.html#cb78-5" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">ungroup</span>()</span>
<span id="cb78-6"><a href="modulo-2.html#cb78-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-7"><a href="modulo-2.html#cb78-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb78-8"><a href="modulo-2.html#cb78-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir el DataFrame a una serie de tiempo en R</span></span>
<span id="cb78-9"><a href="modulo-2.html#cb78-9" aria-hidden="true" tabindex="-1"></a>ts_data <span class="ot">&lt;-</span> <span class="fu">ts</span>(data<span class="sc">$</span>prom_valle, <span class="at">start =</span> <span class="fu">c</span>(<span class="fu">year</span>(<span class="fu">min</span>(data<span class="sc">$</span>fecha)), <span class="fu">month</span>(<span class="fu">min</span>(data<span class="sc">$</span>fecha))), <span class="at">frequency =</span> <span class="dv">12</span>)</span></code></pre></div>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="modulo-2.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(prophet)</span></code></pre></div>
<pre><code>## Warning: package &#39;prophet&#39; was built under R version 4.2.3</code></pre>
<pre><code>## Loading required package: Rcpp</code></pre>
<pre><code>## Loading required package: rlang</code></pre>
<pre><code>## Warning: package &#39;rlang&#39; was built under R version 4.2.3</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="modulo-2.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el dataframe para Prophet</span></span>
<span id="cb84-2"><a href="modulo-2.html#cb84-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">ds =</span> data<span class="sc">$</span>fecha, <span class="at">y =</span> data<span class="sc">$</span>prom_valle)</span>
<span id="cb84-3"><a href="modulo-2.html#cb84-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-4"><a href="modulo-2.html#cb84-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar el modelo Prophet</span></span>
<span id="cb84-5"><a href="modulo-2.html#cb84-5" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">prophet</span>(df)</span></code></pre></div>
<pre><code>## Disabling daily seasonality. Run prophet with daily.seasonality=TRUE to override this.</code></pre>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="modulo-2.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar la predicción para los próximos 4 períodos</span></span>
<span id="cb86-2"><a href="modulo-2.html#cb86-2" aria-hidden="true" tabindex="-1"></a>future <span class="ot">&lt;-</span> <span class="fu">make_future_dataframe</span>(model, <span class="at">periods =</span> <span class="dv">4</span>, <span class="at">freq =</span> <span class="st">&quot;month&quot;</span>)</span>
<span id="cb86-3"><a href="modulo-2.html#cb86-3" aria-hidden="true" tabindex="-1"></a>forecast <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, future)</span>
<span id="cb86-4"><a href="modulo-2.html#cb86-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-5"><a href="modulo-2.html#cb86-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizar los resultados</span></span>
<span id="cb86-6"><a href="modulo-2.html#cb86-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model, forecast)</span></code></pre></div>
<p><img src="Propuesta-Bookdown_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<p>Basándonos en lo que hemos hecho anteriormente, podemos llegar a las siguientes conclusiones:</p>
<ol style="list-style-type: decimal">
<li><p>Los modelos ARIMA y SARIMAX proporcionaron ajustes razonables a los datos de la serie de tiempo de precios del maracuyá. Estos modelos tuvieron en cuenta la autocorrelación y la estacionalidad de los datos, lo que les permitió capturar los patrones y realizar pronósticos.</p></li>
<li><p>Sin embargo, al aplicar el algoritmo Facebook’s Prophet, obtuvimos resultados más precisos y más fáciles de interpretar. Prophet es capaz de manejar las tendencias no lineales y las estacionalidades cambiantes presentes en los datos de la serie de tiempo. Además, nos proporcionó intervalos de confianza para los pronósticos, lo que nos permitió evaluar la incertidumbre asociada a las predicciones.</p></li>
<li><p>La variable en serie de tiempo, representada por los precios del maracuyá, puede ser vista como una regresión en el contexto de Prophet. El modelo de Prophet descompone la serie de tiempo en componentes de tendencia, estacionalidad y efectos de días festivos, y utiliza un modelo aditivo para capturar la relación entre los predictores y la variable objetivo. En nuestro caso, podríamos considerar variables adicionales, como el clima, la oferta y la demanda, como predictores en el modelo de Prophet para mejorar las predicciones.</p></li>
<li><p>Al comparar el ajuste de los diferentes modelos (ARIMA, SARIMAX y Prophet) y su capacidad para realizar pronósticos precisos, encontramos que Prophet superó a los modelos ARIMA y SARIMAX en términos de precisión y facilidad de uso. Sin embargo, es importante tener en cuenta que la elección del modelo depende de las características específicas de los datos y los objetivos del análisis.</p></li>
</ol>
<p>En resumen, hemos aplicado y comparado diferentes modelos de series de tiempo para pronosticar los precios del maracuyá. Encontramos que el algoritmo Facebook’s Prophet proporcionó resultados más precisos y fáciles de interpretar en comparación con los modelos ARIMA y SARIMAX. Esto demuestra la utilidad de Prophet para el análisis y pronóstico de series de tiempo con patrones complejos. Además, identificamos la variable en serie de tiempo como una regresión en el contexto de Prophet, lo que nos permite considerar predictores adicionales para mejorar las predicciones.</p>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="modulo-1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modulo-3.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": false,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
